const {useEffect,useState}=React;
const ods=[['04','Educação','Garantir educação inclusiva, equitativa e de qualidade.'],['10','Desigualdades','Promover inclusão e reduzir desigualdades.'],['11','Comunidades','Valorizar patrimônio cultural e comunidades sustentáveis.'],['16','Direitos','Ampliar acesso à informação e instituições inclusivas.']];
const contents=[{id:1,title:'História e identidade',cat:'História',text:'Conteúdo introdutório sobre identidade, memória coletiva e presença Kanela no Maranhão.'},{id:2,title:'Saberes e patrimônio',cat:'Cultura',text:'Artesanato, narrativas, conhecimentos tradicionais e referências culturais.'},{id:3,title:'Educação escolar indígena',cat:'Educação',text:'Materiais e referências para práticas educativas contextualizadas.'},{id:4,title:'Território e comunidade',cat:'Território',text:'Informações educativas sobre território, comunidade e proteção dos direitos.'},{id:5,title:'ODS e povos indígenas',cat:'ODS',text:'Como os Objetivos de Desenvolvimento Sustentável dialogam com a realidade indígena.'}];
function go(p){location.hash=p}
function Layout({children,page}){const [open,setOpen]=useState(false);return <><header><div className="nav"><button className="brand" onClick={()=>go('inicio')}>◈ <span>Kanela ODS</span></button><button className="menuBtn" onClick={()=>setOpen(!open)} aria-label="Abrir menu">☰</button><nav className={open?'open':''}>{[['inicio','Início'],['ods','ODS'],['cultura','Cultura'],['territorio','Território'],['busca','Busca']].map(([id,t])=><button className={page===id?'active':''} key={id} onClick={()=>{go(id);setOpen(false)}}>{t}</button>)}</nav></div></header><main>{children}</main><footer>Projeto acadêmico • Kanela ODS 2.0 • React + Fetch API + JSON</footer></>}
function Hero(){return <section className="hero"><div><span className="eyebrow">ODS 4 • Educação de qualidade</span><h1>Educação, cultura e memória do povo Kanela</h1><p>Aplicação web educativa que conecta os ODS às realidades, conhecimentos e direitos dos povos indígenas Kanela de Fernando Falcão, Maranhão.</p><div className="actions"><button className="primary" onClick={()=>go('ods')}>Conhecer o ODS</button><button className="secondary" onClick={()=>go('busca')}>Explorar conteúdos</button></div></div><div className="heroArt"><div className="sun"/><div className="hill a"/><div className="hill b"/><div className="basket"/><small>Identidade visual inspirada em elementos naturais e artesanais.</small></div></section>}
function ApiMini(){const [data,setData]=useState(null),[err,setErr]=useState('');useEffect(()=>{fetch('https://servicodados.ibge.gov.br/api/v1/localidades/municipios?nome=Fernando%20Falcao').then(r=>{if(!r.ok)throw Error();return r.json()}).then(j=>setData(j[0])).catch(()=>setErr('Não foi possível consultar a API agora.'));},[]);return <div className="apiBox"><strong>IBGE • JSON</strong>{!data&&!err?<p>Consultando dados externos...</p>:err?<p className="error">{err}</p>:<><h3>{data.nome} - MA</h3><p>ID do município: <b>{data.id}</b></p><small>Resposta JSON tratada pelo React.</small></>}</div>}
function Home(){return <><Hero/><section className="light"><div className="heading"><span className="eyebrow dark">Nota 02</span><h2>Agora a aplicação é interativa</h2><p>O projeto da Nota 01 foi transformado em uma SPA com componentes React, eventos, busca dinâmica, dados externos e interface responsiva.</p></div><div className="grid cards">{ods.map(x=><article key={x[0]}><b className="badge">{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="apiPreview"><div><span className="eyebrow">Dados externos</span><h2>Território consultado em API</h2><p>A aplicação consulta a API de localidades do IBGE para demonstrar Fetch, JSON, carregamento e tratamento de erro.</p></div><ApiMini/></section></>}
function Ods(){return <section className="page light"><span className="eyebrow dark">Objetivos relacionados</span><h1>ODS e educação indígena</h1><p>O ODS 4 é o eixo principal, com diálogo com redução das desigualdades, comunidades sustentáveis e instituições inclusivas.</p><div className="grid cards">{ods.map(x=><article key={x[0]}><b className="badge">{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></section>}
function Cultura(){return <section className="page"><span className="eyebrow dark">Memória e conhecimento</span><h1>Cultura como parte da aprendizagem</h1><p>O sistema organiza conteúdos educativos sobre história, território, práticas culturais e participação social.</p><div className="grid contentGrid">{contents.slice(0,3).map(c=><article className="feature" key={c.id}><span>{c.cat}</span><h2>{c.title}</h2><p>{c.text}</p><button className="linkBtn" onClick={()=>alert('Conteúdo selecionado: '+c.title)}>Ler conteúdo</button></article>)}</div></section>}
function Territorio(){return <section className="page dark"><span className="eyebrow">Território e comunidade</span><h1>Fernando Falcão e a presença Kanela</h1><p>A interface apresenta informações territoriais e utiliza a API do IBGE como demonstração de dados externos.</p><div className="grid contentGrid"><ApiMini/><article className="stat"><strong>125.576,87 ha</strong><p>Área indicada na documentação utilizada na Nota 01.</p></article></div></section>}
function Busca(){const [q,setQ]=useState(''),[cat,setCat]=useState('Todos');const filtered=contents.filter(c=>(cat==='Todos'||c.cat===cat)&&`${c.title} ${c.text}`.toLowerCase().includes(q.toLowerCase()));return <section className="page light"><span className="eyebrow dark">Interatividade</span><h1>Busca de conteúdos</h1><div className="searchbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite uma palavra-chave..."/><select value={cat} onChange={e=>setCat(e.target.value)}><option>Todos</option><option>História</option><option>Cultura</option><option>Educação</option><option>Território</option><option>ODS</option></select></div><p>{filtered.length} resultado(s) encontrado(s).</p><div className="grid contentGrid">{filtered.map(c=><article className="feature" key={c.id}><span>{c.cat}</span><h2>{c.title}</h2><p>{c.text}</p></article>)}{!filtered.length&&<article className="empty">Nenhum conteúdo encontrado. Tente outro termo.</article>}</div></section>}
function App(){const [page,setPage]=useState(location.hash.slice(1)||'inicio');useEffect(()=>{const f=()=>setPage(location.hash.slice(1)||'inicio');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);let C={inicio:Home,ods:Ods,cultura:Cultura,territorio:Territorio,busca:Busca}[page]||Home;return <Layout page={page}><C/></Layout>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
